apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
spec:
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
      - name: shoppingapi
        image: julianecheverri23/shoppingapi
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env: 
         - name: ASPNETCORE_ENVIRONMENT
           value: Development
         - name: DatabaseSettings__ConnectionString
           valueFrom:
               configMapKeyRef:
                 name: mongo-configmap
                 key: connection_string
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
  - port: 5041
    targetPort: 80
    protocol: TCP
    nodePort: 31000
